### ISSUE TITLE
elapsed_days should be a local variable

### ISSUE THREAD

**Issue by lex-neufeld** [open-spaced-repetition/py-fsrs#24]
Currently, Card.elapsed_days is stored persistantly as a member variable. But its value is only true for an instant in time, so any time it is used it must be recalculated first.  It is initialized to 0, but then set to 0 again when parsing Cards with Card.state == State.New to avoid errors. Storing it persistantly has no value and can cause errors.

elapsed_days could isntead be a local variable (initialized to 0) in FSRS.repeat()

**Comment by lex-neufeld** [comment]
note that SchedulingCards.record_log() is using Card.elapsed_days, so that would have to be refactored as well. 

Probably still better than pulling a meaningless Card.elapsed_days from the database, making a deep copy of, updating it to a meaningful value, and then making 4 more deep copies of it, and then writing the value back to the database after it is meaningless again.

**Comment by L-M-Sherlock** [comment]
PR is welcome.

**Comment by L-M-Sherlock** [comment]
I close this issue because `elapsed_days` has been stored persistently as a member variable in ts-fsrs and go-fsrs. I don't want to refactor them all. So I keep the current implementation as it is.

**Comment by domino14** [comment]
@L-M-Sherlock how do you recommend we use `elapsed_days`? Should the value be recalculated as soon as the card is loaded from the database? Will the algorithm not work if we don't do this?

**Comment by joshdavham** [comment]
@domino14 `elapsed_days`, as belonging to the `Card` object is currently mainly an internal variable used for scheduling: you do not need to worry about it. If however, you're looking to simply compute how many days it's been since the card was last reviewed, I'd just do something like `time_since_last_review = datetime.now(timezone.utc) - card.last_review`. I would not recommend touching `elapsed_days`.
